### ISSUE TITLE
Pihustus (PA) kui annustamisühik

### ISSUE THREAD

**Issue by vindrek** [TEHIK-EE/ig-ee-medication-scheme#10]
RETS saadab annustamisühiku võimaliku väärtusena "PU" ehk pihustus. See väärtus on aga retsept-annustamise-yhik loendist puudu.

Kas see on taotluslik muudatus? Kui jah, siis sellisel juhul peab RETS muutuma. Kui näpuviga, siis tuleks loendisse lisada.

**Comment by KristiinaKuldkepp** [comment]
Loendist on näha, et 31.03.2023 on "pihustus" muudetud kehtetuks ning asendatud mõistega mõõtannus (MA). Taotluslik muudatus Tervisekassa poolt.

**Comment by rlindstrm** [comment]
FHIRi mõistes on nii, et ValueSetis on ainult kehtivad mõisted, aga CodeSystemis peaks ka mitteaktiivsed olemas olema, nii et vanemate andmete puhul midagi katki ei läheks.

**Comment by vahurmetsala** [comment]
Vanade andmete kuvamiseks saab kasutada CodeSystem kõiki väärtuseid, vormi peal TJT-s kuvamiseks muutmisel tuleb mõelda välja lahendus. Mure võiks olla eelkõige TJT poolele, vajab UX lahendust.

**Comment by KristiinaKuldkepp** [comment]
lahendatud.
