### ISSUE TITLE
Classification extension peab olema üldisem kui atc

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/ig-ee-medication-scheme#12]
Extensioni kirjelduses on atc vaid üks näide.
Medicationi peal võib olla mitu korda sama extension kasutuses, iga kord anda talle konkreetne nimi "nt ATC" ja lisada binding, mis sobib sellesse kohta.

**Comment by KristiinaKuldkepp** [comment]
kas siis Extensionis endas tuleks atc panna example bindinguga ja mujal siis (vt TEHIK-EE/ig-ee-medication-scheme#15) required? @rlindstrm
