### ISSUE TITLE
Medication profiilid lahku lüüa

### ISSUE THREAD

**Issue by vahurmetsala** [TEHIK-EE/ig-ee-medication-scheme#13]
Sõltuvalt otsusest on meil vaja erinevaid profiile:
- Ravimiskeemis salvestatav - TJT patsiendi sõnul ja ilma müügiloata ravimid
- Retseptikeskuse ravimi profiil
- Ravimiregistri pakendi profiil?
- (võib-olla) vahekihi ehk pakendist tuletatav 

Siin on vaja analüüsida, ja esmalt välja selgitada, milline hakkab olema valideerimise mudel FHIR serveris.

**Comment by KristiinaKuldkepp** [comment]
Teemaks pigem haiglaravimite puhul
