### ISSUE TITLE
extensionEETISSubstitutionAllowed - nimetamise vasturääkivus ja kasutamise loogika

### ISSUE THREAD

**Issue by vahurmetsala** [TEHIK-EE/ig-ee-medication-scheme#21]
Meil on mudel:
MedicationStatement.extension:extensionEETISSubstitutionAllowed
substitutionAllowed: boolean
substitutionAllowedReason: enum https://fhir.ee/CodeSystem/ravimi-asendamatuse-pohjus KP01-KP09

Tegemist on väärtusega, mida märgitakse siis kui asendamine on keelatud. Muidu oleks võimalik kahtepidi lugeda substitutionAllowed, kuid substitutionAllowedReason ei ole loogiline nimetus kui põhjendus on miks ei tohi asendada. Õigem oleks substitutionForbiddenReason?
  
Extension kasutamine oleks igal juhul explicit - alati on extension kaasa pandud, kas asendamine on siis lubatud või keelatud aga data on igal juhul märgitud.

**Comment by KristiinaKuldkepp** [comment]
Extension on tehtud võimalikult sarnane MedicationRequesti substitution (allowed ja reason) elemendiga. Võimalus oleks panna nimeks substitutionReason nagu Med.Requestis (MedicationRequest.substitution.reason)?

**Comment by vindrek** [comment]
Teen ettepaneku extensioni nimeks extensionEETISSubstitution või extensionEETISSubstitutionSpec kui eriti peen olla. Ja selle sees võiks siis omakorda olla substitutionAllowed ja substitutionReason nagu praegugi.

**Comment by rlindstrm** [comment]
Tehtud
