### ISSUE TITLE
Näidetes ja profiilides CodeSystem URL väärtused erinevad

### ISSUE THREAD

**Issue by vahurmetsala** [TEHIK-EE/ig-ee-medication-scheme#23]
Näidetes: http://fhir.ee/CodeSystem/retsepti-liik
Mudelis: https://fhir.ee/CodeSystem/retsepti-liik

Näidetes: http://fhir.ee/CodeSystem/retsepti-kordsus
Mudelis: https://fhir.ee/CodeSystem/retsepti-kordsus

Näidetes: http://fhir.ee/CodeSystem/rhk-10
Mudelis: https://fhir.ee/CodeSystem/rhk10

http://fhir.ee/CodeSystem/retsepti-soodustuse-maar -> peaks ilmselt olema https nagu kõik teised

**Comment by rlindstrm** [comment]
Need peaks olema kõik ühtlustatud nüüd, ning profiilides kasutusel VS ning reaalandmestikus CS.
Kui kuskilt veel leiab mingeid erisusi, siis võiks eraldi teada anda.
