### ISSUE TITLE
EETISMedicationStatement.status väärtused?

### ISSUE THREAD

**Issue by vahurmetsala** [TEHIK-EE/ig-ee-medication-scheme#25]
profiilis on mudel:
EETISMedicationStatement.status
Väärtus on code ning võimalikud väärtused recorded | entered-in-error | draft
 
Teiselt poolt Simplifier definitsiooni all on võimalike väärtustena defineeritud KINNITATUD | KINNITAMATA

mis on õiged?

**Comment by rlindstrm** [comment]
@KristiinaKuldkepp 
.status on required bindinguga HL7 koodidele.
Kinnitatud/kinnitamata peaks seega mäppuma kas nende koodide vastu või siis on vaja ärilist staatust kuskile eraldi.

**Comment by KristiinaKuldkepp** [comment]
jah, ongi mõeldud mäppumiseks, aga ma ei oska mingit eraldi mäpingut teha

**Comment by rlindstrm** [comment]
Kas me saame tekstiliselt öelda, et "Kinnitatud" on recorded ja "Kinnitamata" on draft?
Kas see alati pädeks?
@vahurmetsala @KristiinaKuldkepp

**Comment by vahurmetsala** [comment]
Mina olen hetkel tegutsenud eeldusel, et Kinnitatud ehk recorded on rida, kus ei ole kinnitamata sisu.
See tähendaks, et "kinnitamata" ehk draft on selline rida, mis on kas kinnitamata, või mida on muudetud ja ei ole veel kinnitatud?

Sellisel juhul tunduks, et mäpping võiks olla õige?

**Comment by KristiinaKuldkepp** [comment]
mina olen asjast sama moodi aru saanud nagu @vahurmetsala. Kõik muudatused-sisestamised-kustutamised on seniks draft(=kinnitamata) kuni nad ära kinnitatakse

**Comment by rlindstrm** [comment]
Kui Retseptikeskusest tuleva retsepti põhjal tekitatakse rida, kas see on kinnitatud või kinnitamata? Draft oleks ta kohta nagu ebaõiglane öelda?

**Comment by KristiinaKuldkepp** [comment]
Mina ütleks, et siis on ta recorded=kinnitatud kuniks mõnele arstile see enam ei meeldi ja ta hakkab rida muutma/kustutama vms.

**Comment by rlindstrm** [comment]
Mäping lisada short kirjeldusse ja pikk jutt RKst tulevast kinnitatud reast definitionisse.

**Comment by vahurmetsala** [comment]
Lisada Detailsesse kirjeldusse juurde Retseptikeskuse retsepti alusel genereeritud rea status

**Comment by KristiinaKuldkepp** [comment]
tehtud
