### ISSUE TITLE
MedicationStatement näidete üle toomisel Simplifier'st tuleks eemaldada neilt MedcationStatment.effective.end

### ISSUE THREAD

**Issue by vahurmetsala** [TEHIK-EE/ig-ee-medication-scheme#27]
Hetkel on  https://simplifier.net/ee-tis/~resources?category=Example&exampletype=MedicationStatement&sortBy=RankScore_desc näidetes kõikidel märgitud ka effective.end, kuigi tänaseks on teada, et see tähistab ravimiskeemi rea ärilist lõppu ehk peitu minemist või eemaldamist sellest kuupäevast. 
Fikseeritud ravikuuriga on ravimiskeemi real Dosage all määratud Bounds, see aga ei tähenda, et ravimiskeemi rida peaks lõppema automaatselt, ärikokkulepe oli, et neid tuleb käsitsi eemaldada, mille peale tekib effective.end andmetesse.

**Comment by rlindstrm** [comment]
Effective.end FSH failides välja kommenteeritud, näidissõnumites seda enam ei ole.
