### ISSUE TITLE
Mitme pakendi sisuga ravimid

### ISSUE THREAD

**Issue by vahurmetsala** [TEHIK-EE/ig-ee-medication-scheme#39]
Täna on teatud preparaatidel mitu n.ö. "pakendi sisu" ja sellest tulenevalt ei kuvata jääki ka korrektselt. 

Mõned näited preparaatidest: TRI-REGOL, QLAIRA, CANIFUG CREMOLUM

Sellest tulenevalt on ravimiga seotud mitu Quantity't, kokkupuutekohad:

- väli totalVolume (andmetüüp Quantity, system=https://fhir.ee/CodeSystem/retsept-mahu-ja-massiyhik) (siia saaks panna mitu väärtust?)
extension'id:
- https://fhir.ee/StructureDefinition/ee-tis-total-prescribed-amount (integer)
- uuemas profiilis on tegelikult 0..* Quantity ehk et siia saaks pitu väärtust panna

- https://fhir.ee/StructureDefinition/ee-tis-medication-left (integer)
- see ei lähe arvesse, kuna tegemist on päevade arvuga, 

- https://fhir.ee/StructureDefinition/ee-tis-size-of-item (Quantity, system=https://fhir.ee/CodeSystem/retsept-mahu-ja-massiyhik)
- siin oleks vaja profiili täiendust, et saaks panna mitu väärtust

- medication.totalVolume (Quantity, system=https://fhir.ee/CodeSystem/retsept-mahu-ja-massiyhik)
- siia saaks samuti mitu väärtust panna?

**Comment by rlindstrm** [comment]
Saad Sa täpsustada, et kuidas Sinu arvates siis see Medication välja näeks? Et kuidas sealt aru saaks mitu tabletti on ühte ja mitu teist? Või kui see ei ole oluline, siis miks ei võiks üldse tablette kokku arvutada?

Canifug Cremolumi puhul oleks tõesti nii, et kokku täiesti erinevaid asju lugeda ei saa. 

IHE/HL7 Euroopa grupiga meil on muidu tehtud nested Medication selliste asjade jaoks, aga mu arust tänane ravimiregister ei võimalda seda ka täies mahus tekitada. ([IHE profiil](https://build.fhir.org/ig/IHE/pharm-mpd/StructureDefinition-IHEMedication.html), [IHE näide](https://build.fhir.org/ig/IHE/pharm-mpd/Medication-02A-ClotrimazoleCanifugCremolum.html))

**Comment by KristiinaKuldkepp** [comment]
Medication.totalVolume on FHIR poolt piiritletud 0..1 - ei saa muuta nii, et mitu quantityt. Ma oleks poolt, et teha IHE moodi. Siis jääks totalVolume tühjaks ja item'i all oleks siis nii mitu erinevat medicationit kui vaja. Aga kui ravimiregister on probleemiks, siis lihtsustatul arvutaks tabletid kõik kokku (Tri-Regol ja Qlaira) ja Canifug Cremolum totalVolume oleks 1? Sest viimase puhul pole ju vaja jääki arvutada? Ta kas on või ei ole.

**Comment by vahurmetsala** [comment]
@rlindstrm mul see väike asi jäi tähelepanuta, et doseForm on eraldi loend ja siis on koguseid ja ravimvormi kokku viia väga raske, sest ei ole teada, kumb vorm käib kumma koguse kohta.
Kui ravimvorm on sama, siis saab tabletid kokku lugeda, sest kuur on järjest.
Kui ravimvorm on erinev, siis ma pole päris kindel mida tegema peaks, või kuidas korrektne oleks teha.. Täna võetakse esimese pakendi sisu ja minnakse sellega edasi.

Ma saan minna äripoole juurde ja uurida nende seisukohta - kuidas teie vaatest oleks kõige korrektsem edasi minna? Nested Medication lahendus tundub pigem tuleviku teema...

**Comment by rlindstrm** [comment]
Vabandust, olen maha maganud selle teema.
Ma arvan, et see jäägiarvutus on pigem relevantne neil ravimitel, kus on kõik sama ravimvormiga (tabletid). Need kombinatsioonid, kus on kreem ja tabletid jms, on suht harvad ja pigem vist ühe piiritletud kuuri jaoks. Pole mõtet üle mõelda.

**Comment by vahurmetsala** [comment]
Hetke seis on järgmine (20.09.2024).
* Retseptikeskuses on probleem üleval aga otsest lahendust ei ole
* Kuna RK võtab vastu retsepte, kus on toodud ainult esimene pakendi sisu ja ravimi koguhulk sealt pealt, siis Ravimiskeemi teenuses (MedIN) on kasutusel lahendus, kus eeldatakse FHIR andmetesse ühte pakendi sisu.
* TJT võtab hetkel ravimiregistri andmestiku ja sealt esimese pakendi sisu ning saadab ainult selle FHIR andmetsse
* @vahurmetsala paneb IG-sse eraldi kirja, et seda sorti ravimitel, kus on mitu pakendi sisu, tuleb FHIR andmeid täita ainult esimese pakendi sisu alusel
