### ISSUE TITLE
lastUpdated patternInstant profiilides üleliigne

### ISSUE THREAD

**Issue by LordzShadow** [TEHIK-EE/ig-ee-medication-scheme#42]
Hetkel on järgnevates profiilides määratud `lastUpdated` välja juurde `patternInstant`
- [EETISMedicationEPC](https://build.fhir.org/ig/TEHIK-EE/ig-ee-medication-scheme/StructureDefinition-ee-tis-medication-epc.html)
- [EETISMedicationDispensedToPatient](https://build.fhir.org/ig/TEHIK-EE/ig-ee-medication-scheme/StructureDefinition-ee-tis-medication-dispensed-to-patient.html)
- [EETISMedicationExtemporal](https://build.fhir.org/ig/TEHIK-EE/ig-ee-medication-scheme/StructureDefinition-ee-tis-medication-extemporal.html)

See aga ei ole korrektne, sest see määrab täpse väärtuse, mis see olla võib. Ehk hetkel saaks teha ravimit ainult ajahetkel `2024-02-13T09:25:49.780106+00:00`

[ElementDefinition.pattern[x]](https://www.hl7.org/fhir/elementdefinition-definitions.html#ElementDefinition.pattern_x_) - instant on primitiiv

**Comment by KristiinaKuldkepp** [comment]
<img width="574" alt="image" src="https://github.com/user-attachments/assets/d6afea4e-fded-4c6a-a7f4-6ae0064fce07">
see koht korda teha @KristiinaKuldkepp

**Comment by KristiinaKuldkepp** [comment]
eemaldatud profiilidest
