### ISSUE TITLE
Patient viited ja profiilid

### ISSUE THREAD

**Issue by vahurmetsala** [TEHIK-EE/ig-ee-medication-scheme#6]
Ravimite FHIR serveris ei peaks üldse patsiendi andmetega tegelema, siin peaks olema ainult MPI viited.
Vaja otsustada, kas siin on üldse patsiendi profiile vaja, kui tegemist on reference-ga.

Hea oleks package'na MPI asjadele saada viidata. Ilus oleks ka kitsendada ainult MPI viidetele.

**Comment by vahurmetsala** [comment]
Toetuma peaks vist EEBASEPatient'le aga kui lähenb eemaldamisele, siis vist ei ole üldse vaja?

**Comment by vahurmetsala** [comment]
Otsustati, et hakatakse kasutama reference = "Patient/123" ning kõik süsteemid peavad teadma, et TIS kontekstis on see alati MPI viide, ehk MPI ID. 
Profiilides ära muuta kirjeldus, et tegemist on MPI viitega (link panna?). 
Profiili tasemel on tegemist external reference'ga. Ei tohiks olla contained

**Comment by KristiinaKuldkepp** [comment]
Ma vahetaks nüüd ära kõik EEBasePatient ja EETISPatient viited ee-mpi-patient-verified vastu. Kas keegi näeb selles probleeme tekkivat? @vahurmetsala ja @rlindstrm? (Lõpuks õnnestus mul ka MPI dependency package lisada IG-sse.)

**Comment by vahurmetsala** [comment]
Vastupidi - see oleks väga hea, ma pidin nii ehk naa tulema selle juurde, et me varsti peaksime oma FHIR serverisse sisse viima n.ö. lõplikud profiilid - kirjutan selle kohta ka eraldi

**Comment by KristiinaKuldkepp** [comment]
MPI package lisatud IG-sse, kõik patsiendi viited tehtud ee-mpi-patient-verified vastu.
