### ISSUE TITLE
EETISDeviceTJT alusel teha instants ja profiil eemaldada

### ISSUE THREAD

**Issue by vahurmetsala** [TEHIK-EE/ig-ee-medication-scheme#8]
Juhul kui läheb vaja, siis on viitamine reaalsele Device instantsile.
Vajadus oli peamiselt Composition raames - siin on vaja otsustada, kas seda on üldse vaja ja kus

**Comment by rlindstrm** [comment]
Profiil eemaldatud. Kus vaja, on viidatud lihtsalt Device ressursile.
