### ISSUE TITLE
EETISRelatedPerson vajadus

### ISSUE THREAD

**Issue by KristiinaKuldkepp** [TEHIK-EE/ig-ee-medication-scheme#9]
EETISRelatedPerson on profiilides EETISMedicationRequest (informationSource) ja EETISMedicationStatement  (note author). Kas meil päriselt on usecase relatedPersonile? Kas vahetame viite EEBase RelatedPerson vastu? Või läheks nt dementse patsiendi abikaasa ütluste järgsed ravimid nii kui nii "patsiendi ütluste" alla?

**Comment by rlindstrm** [comment]
Jätame ainult Practitioner ja PractitionerRole, sest patsiendil endal sisestamisvõimalus puudub.

**Comment by rlindstrm** [comment]
MedicationRequestil eemaldada informationSource (Retseptikeskuse retseptil seda ei ole).

**Comment by vahurmetsala** [comment]
EETISMedicationStatement (note author) võiks olla pigem alati spetsialist. 

EETISMedicationRequest (informationSource) puhul ei ole informationSource üldse vajalik, kuna siin tekib kaks eraldi profiili: retsepti oma ja ravimikorralduse oma (hiljem)

**Comment by KristiinaKuldkepp** [comment]
informationSource Prescriptionilt eemaldatud.

**Comment by KristiinaKuldkepp** [comment]
Pole vajadust.
